
-- TIMESTAMP contains DATE and TIME
-- 4 bytes for DATE, 6 for TIME

SELECT CURRENT_TIMESTAMP,
FORMAT(CURRENT_TIMESTAMP);



SELECT *
FROM DBC.QryLogEvents;


SELECT *
FROM DBC.QryLogEvents
WHERE EventTime > CAST('2021-01' AS TIMESTAMP FORMAT 'yyyy-mm');




SELECT *
FROM DBC.QryLogEvents
WHERE EventTime > CAST('2021' AS TIMESTAMP FORMAT 'yyyy');


-- EXTRACT

SELECT 
CURRENT_TIMESTAMP,
EXTRACT(YEAR FROM CURRENT_TIMESTAMP),
EXTRACT(MONTH FROM CURRENT_TIMESTAMP),
EXTRACT(DAY FROM CURRENT_TIMESTAMP),
EXTRACT(HOUR FROM CURRENT_TIMESTAMP),
EXTRACT(MINUTE FROM CURRENT_TIMESTAMP),
EXTRACT(SECOND FROM CURRENT_TIMESTAMP);



-- INTERVAL

SELECT
CURRENT_TIMESTAMP,
CURRENT_TIMESTAMP - INTERVAL '1' YEAR + INTERVAL '1' SECOND;




SELECT 
CURRENT_TIMESTAMP,
CURRENT_TIMESTAMP + INTERVAL '1-02' YEAR TO MONTH, --Notice the dash and 02
CURRENT_TIMESTAMP + INTERVAL '1 01' DAY TO HOUR, 
CURRENT_TIMESTAMP + INTERVAL '1 02:50' DAY TO MINUTE,
CURRENT_TIMESTAMP + INTERVAL '1 02:20:20' DAY TO SECOND;


SELECT 
CURRENT_TIMESTAMP + INTERVAL '01:20' HOUR TO MINUTE,
CURRENT_TIMESTAMP + INTERVAL '01:20:15' HOUR TO SECOND,
CURRENT_TIMESTAMP + INTERVAL '20:15' MINUTE TO SECOND;




